<a href="https://colab.research.google.com/github/anup-marka/neural-networks/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np


In [5]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.78340302, 0.91333984, 0.06883852, 0.82671978],
       [0.77564543, 0.65906201, 0.56857069, 0.28829086],
       [0.11387462, 0.8706484 , 0.04095778, 0.68159945]])

In [9]:
np1.dtype


dtype('float64')

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.3880, -1.1448,  0.8077,  0.8036],
        [ 0.7391, -0.5228, -0.9600,  0.1026],
        [ 0.0238,  0.1949,  1.7481, -0.5235]])

In [14]:
tensor_3 = torch.zeros(2,3,4)
tensor_3
tensor_3.dtype

torch.float32

In [13]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7834, 0.9133, 0.0688, 0.8267],
        [0.7756, 0.6591, 0.5686, 0.2883],
        [0.1139, 0.8706, 0.0410, 0.6816]], dtype=torch.float64)

In [21]:
my_torch1 = torch.arange(10)
my_torch1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **Reshape**

In [16]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
myt = my_torch1.view(2,5)
myt

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
myt[1][2] = 119

In [29]:

myt2 = myt.reshape(5,2)
myt2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 3],
        [8, 9]])

In [33]:
myt2[2,1]

tensor(5)

In [34]:
myt2[:,1:]

tensor([[  1],
        [  3],
        [  5],
        [119],
        [  9]])

# Tensor Math

In [35]:

tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [36]:
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [37]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [39]:

tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

tensor_a.add(tensor_b)
tensor_a

tensor([1, 2, 3, 4])

In [40]:
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])